services:
  php:
    image: ${PHP_IMAGE}
    container_name: php_server
    restart: always
    volumes:
      - ./guestbook:/var/www/html
    depends_on:
      - mysql
    networks:
      - guestbook-network
    environment:
      DB_HOST: mysql
    env_file:
      .env.php
  
  mysql:
    image: ${MYSQL_IMAGE}
    container_name: mysql_server
    restart: always
    env_file:
      .env.mysql
    networks:
      - guestbook-network
    volumes:
      - ./guestbook/migration/migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./mysql/data:/var/lib/mysql
  
  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./guestbook/public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - guestbook-network

networks:
  guestbook-network:
    driver: bridge