services:
  php:
    image: my_php_guestbook
    container_name: php_server
    restart: always
    volumes:
      - ./guestbook:/var/www/html
    depends_on:
      - mysql
    networks:
      - guestbook-network
    environment:
      DB_HOST: 
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: 
  
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    networks:
      - guestbook-network
    volumes:
      - ./guestbook/migration/migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./mysql/data:/var/lib/mysql
  
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./guestbook/public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - guestbook-network

networks:
  guestbook-network:
    driver: bridge